-- select * from hr.employees;
    -- 1. Company avg → Dept avg → Employees above dept avg

-- with company_avg as(
--     select avg(salary) as avg_salary
--     from hr.employees
-- ),
-- dept_avg as( 
--     select department_id,avg(salary)as avg_salary
--     from hr.employees
--     group by department_id
-- ),
-- high_earners as(
--     select e.employee_id,e.first_name,e.salary,e.department_id
--     from hr.employees e 
--     join dept_avg d 
--     on e.department_id=d.department_id
--     where e.salary > d.avg_salary
--      and d.avg_salary > (select avg_salary from company_avg)
--    )
-- select * from high_earners;

   -- 2. Dept avg → Rank depts → Top departments → Employees

-- WITH dept_avg AS (
--     SELECT department_id, AVG(salary) AS avg_salary
--     FROM hr.employees
--     GROUP BY department_id
-- ),
-- ranked_depts AS (
--     SELECT department_id,
--            avg_salary,
--            DENSE_RANK() OVER (ORDER BY avg_salary DESC) AS rnk
--     FROM dept_avg
-- ),
-- top_depts AS (
--     SELECT department_id
--     FROM ranked_depts
--     WHERE rnk <= 3
-- )
-- SELECT e.employee_id, e.first_name, e.salary, e.department_id
-- FROM hr.employees e
-- JOIN top_depts t
--   ON e.department_id = t.department_id;

  -- 3. Dept stats → Strong depts → Top earners in dept


-- WITH dept_stats AS (
--     SELECT department_id,
--            COUNT(*) AS emp_count,
--            AVG(salary) AS avg_salary
--     FROM hr.employees
--     GROUP BY department_id
-- ),
-- strong_depts AS (
--     SELECT department_id
--     FROM dept_stats
--     WHERE emp_count >= 3
--       AND avg_salary > 8000
-- ),
-- dept_max AS (
--     SELECT department_id, MAX(salary) AS max_salary
--     FROM hr.employees
--     GROUP BY department_id
-- )
-- SELECT e.employee_id, e.first_name, e.salary, e.department_id
-- FROM hr.employees e
-- JOIN strong_depts s
--   ON e.department_id = s.department_id
-- JOIN dept_max m
--   ON e.department_id = m.department_id
-- WHERE e.salary = m.max_salary;

  -- 4. Company avg → Dept performance → High performing depts

-- WITH company_avg AS (
--     SELECT AVG(salary) AS avg_salary
--     FROM hr.employees
-- ),
-- dept_performance AS (
--     SELECT department_id,
--            AVG(salary) AS avg_salary,
--            COUNT(*) AS emp_count
--     FROM hr.employees
--     GROUP BY department_id
-- ),
-- high_perf_depts AS (
--     SELECT department_id
--     FROM dept_performance
--     WHERE avg_salary > (SELECT avg_salary FROM company_avg)
--       AND emp_count >= 3
-- )
-- SELECT e.employee_id,
--        e.first_name,
--        e.salary,
--        e.department_id
-- FROM hr.employees e
-- JOIN high_perf_depts h
--   ON e.department_id = h.department_id
-- WHERE e.salary > (
--     SELECT AVG(salary)
--     FROM hr.employees e2
--     WHERE e2.department_id = e.department_id
-- );

  -- 5. Company avg → Dept avg → Ranked employees in strong depts

-- with company_avg as (
--     select avg(salary)as avg_salary
--     from hr.employees  -- returns avg sal
-- ),
-- dept_avg as (
--     select department_id,avg(salary)as avg_salary
--     from hr.employees -- caluclate dept avg sal
--     group by department_id
-- ),
-- strong_dept as(
--     select department_id   --- returns dept id where dept avg sal > emp avg sal
--     from dept_avg
--     where avg_salary>(select avg_salary from company_avg)
-- )
-- select employee_id,first_name,salary,department_id,
-- rank()over(partition by department_id order by salary desc)
-- from hr.employees where department_id in (select department_id from strong_dept);

--   6. Company avg → Dept avg → Employees above both averages

-- with company_avg as (
--     select avg(salary)as avg_salary
--     from hr.employees
-- ),
-- dept_avg as (
--     select department_id,
--     avg(salary) as avg_salary
--     from hr.employees
--     group by department_id
-- ),
-- qualified_emp as (
--     select e.employee_id,
--     e.first_name,
--     e.salary,
--     e.department_id
--     from hr.employees e 
--     join dept_avg d 
--     on e.department_id=d.department_id
--     where e.salary > d.avg_salary
--     and e.salary > (select avg_salary from company_avg)
-- )
-- select * from qualified_emp;